Used "inspiration" from the simple python plugin by activestate

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,81 +1,76 @@
 #!/usr/bin/env bash
-# bin/compile <build-dir> <cache-dir>
+# -*- bash -*-
 
+# Fail fast and fail hard.
 set -eo pipefail
 
-# config
-LP_DIR=`cd $(dirname $0); cd ..; pwd`
+# for DEBUG; remove me.
+set -x
 
+# Paths.
 BIN_DIR=$(cd $(dirname $0); pwd) # absolute path
 ROOT_DIR=$(dirname $BIN_DIR)
 BUILD_DIR=$1
 CACHE_DIR=$2
+PYTHON_VERSION=${PYTHON_VERSION:-2.7}
 
-NAME=$($BIN_DIR/detect $BUILD_DIR)
-PIP_DOWNLOAD_CACHE=${PIP_DOWNLOAD_CACHE:-$CACHE_DIR/pip_downloads}
-VENDORED_MEMCACHED="http://cl.ly/0a191R3K160t1w1P0N25/vendor-libmemcached.tar.gz"
-
-indent() {
-  RE="s/^/       /"
-  [ $(uname) == "Darwin" ] && sed -l "$RE" || sed -u "$RE"
-}
+source $BIN_DIR/utils
 
 cd $BUILD_DIR
 
-# reject a non-packaged Django app
-if [ "$NAME" = "Python" ]; then
-  [ -f manage.py ] && [ -f settings.py ] && { echo " !     Django app must be in a package subdirectory"; exit 1; }
+if [[ -f runtime.txt ]]; then
+	# parse something like python-3.2.1 into 3.2
+	PYTHON_VERSION_FULL=$(cat runtime.txt | sed -n 's/python\-\([0-9\.]*\)/\1/p')
+	PYTHON_VERSION=`echo $PYTHON_VERSION_FULL | sed -n 's/\([0-9]\.[0-9]\)\(\.[0-9]\)*/\1/p'`
+
+	if [[ ! -e /opt/ActivePython-$PYTHON_VERSION ]]; then
+		puts-warn "ActivePython-$PYTHON_VERSION is not installed"
+		exit 2
+	fi
+
+	# ensure that we do in fact have PYTHON_VERSION_FULL installed
+	if [ "$PYTHON_VERSION_FULL" != "$PYTHON_VERSION" ]; then
+		actual_version=`/opt/ActivePython-$PYTHON_VERSION/bin/python$PYTHON_VERSION -c 'import sys; print("{0.major}.{0.minor}.{0.micro}".format(sys.version_info))'`
+		if [ "$PYTHON_VERSION_FULL" != "$actual_version" ]; then
+			puts-warn "Requested Python version ($PYTHON_VERSION_FULL) did not match the installed version ($actual_version)"
+			exit 2
+		fi
+	fi
+else
+	if [[ ! -e /opt/ActivePython-$PYTHON_VERSION ]]; then
+		puts-warn "ActivePython-$PYTHON_VERSION is not installed"
+		exit 2
+	fi
 fi
 
-
-# copy artifacts out of cache if exists
-mkdir -p $CACHE_DIR
-
-# create set-aside .heroku folder.
-rm -rf .heroku
-mkdir .heroku
-
-# if pylibmc within requirements, use vendored libmemcached
-if [ -f requirements.txt ]; then
-  if (grep -Fxiq "pylibmc" requirements.txt) || (grep -Fiq "pylibmc=" requirements.txt)
-  then
-    echo "-----> Noticed pylibmc. Bootstrapping libmemcached."
-    cd .heroku
-
-    if [ -d "vendor/lib/sasl2" ]; then
-      export LIBMEMCACHED=$(pwd)/vendor
-    else
-      curl -s -L -O $VENDORED_MEMCACHED
-      tar -zxvf vendor-libmemcached.tar.gz > /dev/null
-      rm vendor-libmemcached.tar.gz
-      export LIBMEMCACHED=$(pwd)/vendor
-    fi
-
-    export LIBMEMCACHED=$(pwd)/vendor
-    cd ..
-  fi
-fi
-
-
-PYTHON_VERSION=${PYTHON_VERSION:-2.7}
-export PYTHONUSERBASE=/app/.python
-export PYTHONUNBUFFERED=True
 APYBIN=/opt/ActivePython-$PYTHON_VERSION/bin
 
-if [ -f requirements.txt ]; then
-  if (grep -Fiq "hg+" requirements.txt) then
-    PIP_DOWNLOAD_CACHE=$PIP_DOWNLOAD_CACHE $APYBIN/pip install $PIP_OPTS mercurial | indent
-  fi
+puts-step "Using Python-$PYTHON_VERSION (ActivePython)"
+
+export PATH=$APYBIN:$PATH
+# Use /app-based for relocation during runtime.
+export PYTHONUSERBASE=/app/.python
+export PYTHONUNBUFFERED=True
+
+if [[ -f requirements.pypm ]]; then
+	puts-step "Installing requirements via PyPM"
+	$APYBIN/pypm install -r requirements.pypm | indent
 fi
 
-if [ -f requirements.txt ];
-then
-	echo "-----> Installing dependencies using pip version $(bin/pip --version | awk '{print $2}')"
-	PIP_DOWNLOAD_CACHE=$PIP_DOWNLOAD_CACHE $APYBIN/pip install $PIP_OPTS -r requirements.txt | indent
+if [[ -f requirements.txt ]]; then
+	puts-step "Installing requirements via pip"
+	$APYBIN/pip install $PIP_OPTS --user --use-mirrors -r requirements.txt | cleanup_pip | indent
 fi
 
-$APYBIN/pip install sphinx $PIP_OPTS
-$APYBIN/pip install oauth2==1.5.211 Flask==0.8 Flask-OpenID==1.0.1 python-openid==2.2.5 $PIP_OPTS
+puts-step "Installing sphinx via pip"
+$APYBIN/pip install sphinx $PIP_OPTS | cleanup_pip | indent
+puts-step "Installing web server requirements via pip"
+$APYBIN/pip install oauth2==1.5.211 Flask==0.8 Flask-OpenID==1.0.1 python-openid==2.2.5 $PIP_OPTS | cleanup_pip | indent
+
+puts-step "Building runtime environment"
+mkdir -p $BUILD_DIR/.profile.d
+echo "export PYTHON_VERSION=$PYTHON_VERSION; PATH=\"$PYTHONUSERBASE/bin:$APYBIN:\$PATH\"; export PYTHONUSERBASE=$PYTHONUSERBASE; export PYTHONUNBUFFERED=True" > $BUILD_DIR/.profile.d/python.sh
+
 CONF_FILE=$(find . -name 'conf.py' | head -1)
 PROJECT=$(dirname $CONF_FILE)
 pushd $PROJECT
